ProjMyWebsite/AppAboutMe/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from AppAboutMe import views

app_name = 'aboutme'

urlpatterns = [url(r'^$', views.AboutMeView.as_view(), name='aboutme')]

ProjMyWebsite/AppBlog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from AppBlog import views

app_name = 'blog'

urlpatterns = [url(r'^$', views.PostListView.as_view(), name='postmodel_list'),
               url(r'^about/$', views.AboutView.as_view(), name='about'),
               url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(),
                   name='postmodel_detail'),
               url(r'^post/new/$', views.CreatePostView.as_view(),
                   name='postmodel_new'),
               url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(),
                   name='postmodel_edit'),
               url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(),
                   name='postmodel_remove'),
               url(r'^drafts/$', views.DraftListView.as_view(),
                   name='postmodel_draft_list'),
               url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post,
                   name='add_comment_to_postmodel'),
               url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve,
                   name='comment_approve'),
               url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove,
                   name='comment_remove'),
               url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish,
                   name='postmodel_publish'),
                   ]

ProjMyWebsite/AppContact/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from AppContact import views

app_name = 'contact'

urlpatterns = [url(r'^$', views.ContactMeView.as_view(), name='contactme')]

ProjMyWebsite/AppSamples/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from AppSamples import views

app_name = 'samples'

urlpatterns = [url(r'^$', views.SamplesView.as_view(), name='samples'),

               ]

ProjMyWebsite/ProjMyWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from AppAboutMe.views import AboutMeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', AboutMeView.as_view(), name='aboutme'),
    url(r'index/', include('AppIndex.urls')),
    url(r'^aboutme/', include('AppAboutMe.urls')),
    url(r'^samples/', include('AppSamples.urls')),
    url(r'^contact/', include('AppContact.urls')),
    url(r'^todolist/', include('AppToDo.urls')),
    url(r'^blog/', include('AppBlog.urls')),
    url(r'^corrstudy/', include('AppCorrStudy.urls')),
    url(r'accounts/login/$', views.login, name='login'),
    url(r'accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'})
]

ProjMyWebsite/AppBlog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


# Create your models here.


class PostModel(models.Model):
    author = models.ForeignKey('auth.User')
# if multiple authors, code would be different.
    title = models.CharField(max_length=50)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)  # tied to line 32

    def get_absolute_url(self):
        # this answers, after a post what page do i show.
        return reverse('blog:postmodel_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class CommentModel(models.Model):
    post = models.ForeignKey('AppBlog.PostModel', related_name='comments')
    author = models.CharField(max_length=50)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:postmodel_list')

    def __str__(self):
        return self.text

ProjMyWebsite/AppBlog/forms.py
# -*- coding: utf-8 -*-

from django import forms
from AppBlog.models import PostModel,CommentModel


class PostForm(forms.ModelForm):

    class Meta():
        model = PostModel
        fields = ('author', 'title', 'text')
        # widget to grab a particular field
        widgets = {'title': forms.TextInput(attrs={'class': 'textinput'}),
                   'text': forms.Textarea(attrs={'class': 'editable\
                                                 medium-editor-textarea\
                                                 postcontent'})}


class CommentForm(forms.ModelForm):

    class Meta():
        model = CommentModel
        fields = ('author', 'text')
        widgets = {'author': forms.TextInput(attrs={'class': 'textinput'}),
                   'text': forms.Textarea(attrs={'class': 'editable\
                                                 medium-editor-textares'})}

ProjMyWebsite/AppBlog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import PostModel, CommentModel
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin  # class based version
from django.contrib.auth.decorators import login_required  # decorator version
from django.views.generic import (TemplateView, ListView, DetailView, CreateView,
                                  UpdateView, DeleteView)
# imports for comments
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages


# Create your views here.
# These views are for the blog posts

class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    model = PostModel
    template_name = 'blog.html'

    # this function searches the database
    def get_queryset(self):
        return PostModel.objects.filter(published_date__lte=timezone.now())\
                                        .order_by('-published_date')


class PostDetailView(DetailView):
    model = PostModel


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/postmodel_detail.html'
    form_class = PostForm
    model = PostModel


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/postmodel_detail.html'
    form_class = PostForm
    model = PostModel


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = PostModel
    success_url = reverse_lazy('blog:postmodel_list')


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/postmodel_list.html'
    model = PostModel

    def get_queryset(self):
        return PostModel.objects.filter(published_date__isnull=True).order_by('created_date')


# These views are for the comments section of the page.

@login_required
def post_publish(request, pk):
    post = get_object_or_404(PostModel, pk=pk)
    post.publish()
    return redirect('blog:postmodel_list')


# @login_required  uncomment to use this line
def add_comment_to_post(request, pk):
    post = get_object_or_404(PostModel, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:postmodel_detail', pk=post.pk)
        else:
            messages.error(request, 'Comment can not be blank')
            return render(request, 'AppBlog/comment_form.html', {'form': form})

    else:
        form = CommentForm()
        return render(request, 'AppBlog/comment_form.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(CommentModel, pk=pk)
    comment.approve()
    return redirect('blog:postmodel_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(CommentMode, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:postmodel_detail', pk=post_pk)

ProjMyWebsite/AppBlog/templates/AppBlog/blog.html
{% extends 'AppBlog/blog_base.html'%}

{% block content %}
<h1 class="display-4">Blog Home</h1>
    {% for post in postmodel_list %}
      <p class="lead">
        <a href="{% url 'blog:postmodel_detail' pk=post.pk %}">
          {{ post.title }}
        </a>
      </p>
      <p>Published on:{{ post.published_date|date:" M d, Y"}}</p>
        <!-- <a href="">Comments: {{ post.approve_comments.count }}</a> -->

    {% endfor %}
</div>


{% endblock%}

ProjMyWebsite/AppBlog/templates/AppBlog/blog_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Gerardo Sandoval</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
    <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

  </head>
  <body class="flex-shrink-0">
    <!-- NavBar -->
    <nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'aboutme:aboutme' %}">Gerardo Sandoval</a>
      <!-- blog navbar section -->
      <nav class="navbar navbar-dark bg-dark">
        <span class="navbar-text">
          {% if user.is_authenticated %}
            <a href="{% url 'blog:postmodel_list' %}">Blog Home   |</a>
            <a class="nav-item" href="{% url 'blog:postmodel_new' %}"> New Post   |</a>
            <a class="nav-item" href="{% url 'blog:postmodel_draft_list' %}">   Drafts   |</a>
            <a class="nav-item" href="{% url 'logout' %}">   Log Out   |</a>
            <!-- <a class="nav-item" href="#">  Welcome: {{user.username}} </a> -->

          {% else %}
            <a href="{% url 'blog:postmodel_list' %}">
              Blog Home   |
            </a>
            <a class="nav-item" href="{% url 'login' %}" aria-label="Login">
              Log In
            </a>
          {% endif %}
        </span>
      </nav>
      <!-- hamburger -->
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1"
        aria-expanded="false" aria-label="Toggle navigation"  name="menuButton">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- hamburger menu options -->
      <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'samples:samples' %}">Portfolio</a>
          <a class="nav-item nav-link" href="{% url 'contact:contactme' %}">Contact Me</a>
        </div>
      </div>
    </nav>
    <br>
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

ProjMyWebsite/AppBlog/templates/AppBlog/comment_form.html
{% extends 'AppBlog/blog_base.html' %}

{% block content %}
<h1>New Comment</h1>
<form class="post-form" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary"> Post Comment</button>
</form>
{% endblock %}

ProjMyWebsite/AppBlog/templates/AppBlog/post_list.html
{% extends 'AppBlog/blog_base.html' %}

{% block content %}
<div class="centerstage">
  {% for post in post_list %}
    <div class="post">
      <h1> <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a> </h1>
      <div class="date">
        <p>Published on: {{post.published|date:"D M Y"}}</p>
      </div>
      <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
    </div>

  {% endfor %}
</div>

{% endblock %}

ProjMyWebsite/AppBlog/templates/AppBlog/postmodel_confirm_delete.html
{% extends 'AppBlog/blog_base.html' %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  <p>Do you want to delete post: {{object}}?</p>
  {{object.text}}
  <br><br>
  <a class="btn btn-secondary" href="{%url 'blog:postmodel_list'%}">Cancel</a>
  <input type="submit" class="btn btn-danger" value="Delete">

</form>

{% endblock %}

ProjMyWebsite/AppBlog/templates/AppBlog/postmodel_detail.html
{% extends 'AppBlog/blog_base.html' %}

{% block content %}

{% if user.is_authenticated %}
  {% if postmodel.published_date %}
    <h3 class="posttitle">{{postmodel.title}}</h3>
    <div class="date postdate">
      {{ postmodel.published_date}}
    </div>
    <br>
    <h5> <p class="postcontent"> {{postmodel.text}}</p></h5>
    <!-- <hr> -->
    <br>
    <a class="btn btn-primary" href="{% url 'blog:postmodel_list' %}">
      Back
    </a>
    <a class="btn btn-secondary" href="{% url 'blog:postmodel_edit' pk=postmodel.pk %}">
      Edit
    </a>
    <a class="btn btn-secondary" href="{% url 'blog:postmodel_remove' pk=postmodel.pk %}">
      Delete
    </a>
  {% else %}
    <h3 class="posttitle">{{postmodel.title}}</h3>
    <div class="date postdate">
      Not Published Yet
    </div>
    <h5> <p class="postcontent"> {{postmodel.text}}</p></h5>
    <hr>
    <a class="btn btn-primary" href="{% url 'blog:postmodel_publish' pk=postmodel.pk %}">
      Publish
    </a>
    <a class="btn btn-secondary" href="{% url 'blog:postmodel_edit' pk=postmodel.pk %}">
      Edit
    </a>
    <a class="btn btn-secondary" href="{% url 'blog:postmodel_remove' pk=postmodel.pk %}">
      Delete
    </a>
  {% endif %}
{% else %}
  <h3 class="posttitle">{{postmodel.title}}</h3>
  <div class="date postdate">
    {{ postmodel.published_date}}
  </div>
  <h5> <p class="postcontent"> {{postmodel.text}}</p></h5>
  <hr>
  <a class="btn btn-primary" href="{% url 'blog:postmodel_list' %}">
    Back
  </a>
{% endif %}

<br> <hr> <br>

<a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_postmodel' pk=postmodel.pk %}">
  Add Comment
</a>


{% for comment in postmodel.comments.all %}
  {% if comment %}
    <br>
    {{ comment.author }}:
    {{ comment.create_date }}
    <br>
  {{ comment.text}}
    {% endif %}
{% empty %}
    <p>No Comments</p>
{% endfor %}


{% endblock %}

ProjMyWebsite/AppBlog/templates/AppBlog/postmodel_draft_list.html
{% extends 'AppBlog/blog_base.html' %}

{% block content %}
{% for post in posts %}
<div class="container">
  <p class="date">Created: {{ post.create_date }}</p>
  <h1> <a href="{% url 'blog:postmodel_detail' pk=post.pk %}">
          {{post.title}}</a>
  </h1>
  <p>{{post.text|truncatechars:200}}</p>
</div>
{% endfor %}

{% endblock %}

ProjMyWebsite/AppBlog/templates/AppBlog/postmodel_form.html
{% extends 'AppBlog/blog_base.html' %}

{% block content %}
<h1>New Post</h1>
<form class="post-form" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-secondary">Save</button>

</form>

{% endblock %}

ProjMyWebsite/AppBlog/templates/AppBlog/postmodel_list.html
{% extends 'AppBlog/blog_base.html' %}

{% block content %}
<div class="centerstage">
  {% for post in post_list %}
    <div class="post">
      <h1> <a href="{% url 'blog:postmodel_detail' pk=post.pk %}">{{post.title}}</a> </h1>
      <div class="date">
        <p>Published on: {{post.published|date:"D M Y"}}</p>
      </div>
      <a href="{% url 'blog:postmodel_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
    </div>

  {% endfor %}
</div>

{% endblock %}