ProjMyWebsite/AppAboutMe/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from AppAboutMe import views

app_name = 'aboutme'

urlpatterns = [url(r'^$', views.AboutMeView.as_view(), name='aboutme')]

ProjMyWebsite/AppBlog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from AppBlog import views

app_name = 'blog'

urlpatterns = [url(r'^$', views.PostListView.as_view(), name='postmodel_list'),
               url(r'^about/$', views.AboutView.as_view(), name='about'),
               url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(),
                   name='postmodel_detail'),
               url(r'^post/new/$', views.CreatePostView.as_view(),
                   name='postmodel_new'),
               url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(),
                   name='postmodel_edit'),
               url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(),
                   name='postmodel_remove'),
               url(r'^drafts/$', views.DraftListView.as_view(),
                   name='postmodel_draft_list'),
               url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post,
                   name='add_comment_to_postmodel'),
               url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve,
                   name='comment_approve'),
               url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove,
                   name='comment_remove'),
               url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish,
                   name='postmodel_publish'),
                   ]

ProjMyWebsite/AppContact/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from AppContact import views

app_name = 'contact'

urlpatterns = [url(r'^$', views.ContactMeView.as_view(), name='contactme')]

ProjMyWebsite/AppSamples/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from AppSamples import views

app_name = 'samples'

urlpatterns = [url(r'^$', views.SamplesView.as_view(), name='samples'),

               ]

ProjMyWebsite/AppToDo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from AppToDo import views

app_name = 'todolist'

urlpatterns = [url(r'^$', views.ToDoListView, name='todolist'),
               url(r'^delete/(?P<pk>\d+)', views.Delete, name='delete'),
               url(r'^cross_off/(?P<pk>\d+)', views.cross_off, name='cross_off'),
               url(r'^uncross/(?P<pk>\d+)', views.uncross, name='uncross'),
               url(r'^edit/(?P<pk>\d+)', views.Edit, name='edit'),
               ]

ProjMyWebsite/ProjMyWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from AppAboutMe.views import AboutMeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', AboutMeView.as_view(), name='aboutme'),
    url(r'index/', include('AppIndex.urls')),
    url(r'^aboutme/', include('AppAboutMe.urls')),
    url(r'^samples/', include('AppSamples.urls')),
    url(r'^contact/', include('AppContact.urls')),
    url(r'^todolist/', include('AppToDo.urls')),
    url(r'^blog/', include('AppBlog.urls')),
    url(r'^corrstudy/', include('AppCorrStudy.urls')),
    url(r'accounts/login/$', views.login, name='login'),
    url(r'accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'})
]

ProjMyWebsite/templates/aboutme.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<!-- Intro -->

<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Welcome to my site!</h1>
    <div class="row">
      <div class="col-md-6">
        <p class="lead">I am searching for a role that will allow me to combine my
          Python programming skills with my 10 years of investment research and
          consulting experience. I enjoy studying data and extracting
          information that you can act on and generate profits from. </p>
      </div>
    </div>
  </div>

   <!-- Resume -->

  <hr class="my-4">
  <div class="accordion" id="accordionExample">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
          data-target="#resume" aria-expanded="false" aria-controls="collapseOne"
          style="color:grey">
            Resume
          </button>
        </h2>
      </div>
      <div id="resume" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body">
          <!-- Resume Section Buttons -->
          <p>
            <button class="btn btn-primary" type="button" data-toggle='collapse'
            data-target='#programming' aria-expanded='false' aria-controls='collapseExample' name="button"
            href="#collapseExample">
            Programming Courses Completed
            </button>
            <button class="btn btn-primary" type="button" data-toggle='collapse'
            data-target='#ubs' aria-expanded='false' aria-controls='collapseExample' name="button"
            href="#collapseExample">
            UBS
            </button>
            <button class="btn btn-primary" type="button" data-toggle='collapse'
            data-target='#jpm' aria-expanded='false' aria-controls='collapseExapmle' name="button"
            href="#collapseExample">
            JP Morgan Private Bank
            </button>
            <button class="btn btn-primary" type="button" data-toggle='collapse'
            data-target='#ml' aria-expanded='false' aria-controls='collapseExapmle' name="button"
            href="#collapseExample">
            Merrill Lynch
            </button>
          </p>
          <!-- Resume Section Body -->
          <div class="collapse" id="programming">
            <div class="card card-body">
              <h3>Programming Courses I have completed:</h3>
              <ul>
                MIT OpenCourseWare
                <ul>
                  <li>Introduction to Computer Science and Programming in Python</li>
                  <li>Introduction to Computational Thinking and Data Science</li>
                </ul>
                Udemy
                <ul>
                  <li>Python and Django Full Stack Web Developer Bootcamp by Pierian Data</li>
                  <li>Python for Financial Analysis and Algorithmic Trading by Pierian Data</li>
                  <li>Python for Finance: Investment Fundamentals & Data Analytics by 365 Careers </li>
                  <li>Python OOP: Four Pillars of OOP in Python by Febin George</li>
                </ul>
                EdX
                <ul>
                  <li>Probability and Statistics in Data Science using Python by UCSD X</li>
                  <li>Python for Data Science by UCSD X</li>
                  <li>Introduction to Python: Creating Scalable, Robust, Interactive Code by Microsoft</li>
                </ul>
              </ul>

            </div>

          </div>
          <div class="collapse" id="ubs">
            <div class="card card-body">
              <h3>UBS</h3>
              <ul>
                <li>Contributed in growing practice from 40MM AUM to over 95MM AUM by providing
                in-depth needs based analysis.</li>
                <li>Developed the group’s methods for analyzing and selecting asset managers.</li>
                <li>Performed due-diligence and ongoing monitoring of equity
                  managers (long only, long short, domestic, international),
                  fixed income managers (traditional bond managers, flexible mandate managers,
                   international FI managers, long short credit), and alternative managers
                   (managed futures, market neutral, global macro strategies, event driven, etc).</li>
                <li>Analyzed portfolios to determine methods of decreasing portfolio volatility,
                  drawdown, and correlations to various assets classes; thus, improving portfolio efficiency.</li>
                <li>Presented to and educated finance committees on investment themes, methods, and rational. </li>
                <li>Monitored markets to determine entry and exit points of portfolio positions.</li>
                <li>Generated, presented, and sold fixed income trade ideas that were responsible for 30% of team’s revenue.</li>
                <li>Used FI360 for benchmarking our DC Plans as part of our ongoing due diligence process.</li>
                <li>Used Zephyr for ongoing due-diligence of funds within our DC Plans.</li>
              </ul>
            </div>
          </div>
          <div class="collapse" id="jpm">
            <div class="card card-body">
              <h3>JP Morgan Private Bank</h3>
              <ul>
                <li>Responsible for a book of over 150MM in client positions.</li>
                <li>Developed investment policy statements for our client’s. </li>
                <li>Increased revenue 15% by developing new business using our investments, lending, and deposit platforms.</li>
                <li>Created Goal Based Wealth Management Plans for clients using software that includes Monte Carlo based technology.</li>
                <li>Communicated the latest research, white papers, and investment themes to clients.</li>
              </ul>
            </div>
          </div>
          <div class="collapse" id="ml">
            <div class="card card-body">
              <h3>Merrill Lynch</h3>
              <ul>
                <li>Educated small business owners on Merrill Edge’s retirement plan solutions (401ks, Simple IRA, SEPs).</li>
                <li>Educated investors on investment topics including but not limited to: margin, fixed income, trade process,
                bid-ask, options, spreads, etc. </li>
                <li>Uncover needs that can be met using BofA’s vast offering of client solutions by using a service to sale dialogue model.</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingTwo">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
          data-target="#aboutme" aria-expanded="false" aria-controls="collapseTwo"
          style="color:grey">
            Beyond the Office
          </button>
        </h2>
      </div>
      <div id="aboutme" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body">
          <p>I live in Elmwood Park with my wife Amy and son Sebastian.
            I enjoy mountain biking, any aquatic sport, and jiu-jitsu.
          </p>
          <p>I grew up in San Diego, CA. Before moving to the midwest i completed an Ironman 70.3!
            <a href="https://www.ironman.com/triathlon/events/americas/ironman-70.3/oceanside/results.aspx?y=2013&rd=20130330&race=california70.3&bidid=776&detail=1#axzz5sRNpQZ00">
              Race Results
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
  <br>
  <p class="lead">
    <!-- <a class="btn btn-secondary btn-lg" href="#" role="button">Learn more</a> -->
  </p>
</div>





{% endblock %}

ProjMyWebsite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Gerardo Sandoval</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
  </head>
  <body class="flex-shrink-0">
    <!-- NavBar -->
    <nav class="navbar navbar-expand-xl fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'aboutme:aboutme' %}">Gerardo Sandoval</a>
      <!-- hamburger -->
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1"
        aria-expanded="false" aria-label="Toggle navigation"  name="menuButton">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- hamburger menu options -->
      <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'samples:samples' %}">Portfolio</a>
          <a class="nav-item nav-link" href="https://github.com/1sandovalgerardo">GitHub</a>
          <a class="nav-item nav-link" href="{% url 'contact:contactme' %}">Contact Me</a>

        </div>
      </div>
    </nav>
    <br><br><br>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

ProjMyWebsite/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Contact Me!</h1>
    <p class="lead">Send an email to:</p>
    <p>1sandoval.contact@gmail.com</p>
  </div>
</div>

{% endblock %}

ProjMyWebsite/templates/corrstudy.html
{% extends 'base.html' %}
  {% block content %}
<div class="jumbotron">
  <h1 class="display-4">Correlation Study Tools</h1>
  <p class="lead">These tools were created to assist in finding periods of high
    correlation between different stocks or within a stock's price movement (seasonality).
  </p>
  <p class="lead"> Here is the link to the source code:
    <a href="https://github.com/1sandovalgerardo/SPY_Underlying_Study">Correlation Study</a>
  </p>

  <p class="lead">Here are three stocks that have some seasonality in their price movement.</p>
</div>
  <table class='table table-bordered table-sm'>
    <thead>
      <tr>
        <th scope="col">Stock</th>
        <th scope="col">Period</th>
        <th scope="col">Number Winners</th>
        <th scope="col">Number Losers</th>
        <th scope="col">Total Trades</th>
        <th scope="col">Avg Return on Winners</th>
        <th scope="col">Avg Return on Loosers</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td scope="row">GOOG</td>
        <td scope="row">Aug-Nov</td>
        <td scope="row">11</td>
        <td scope="row">3</td>
        <td scope="row">14</td>
        <td scope="row">15.95%</td>
        <td scope="row">-13.26%</td>
      </tr>
      <tr>
        <td scope="row">MSFT</td>
        <td scope="row">Oct-Dec</td>
        <td scope="row">11</td>
        <td scope="row">3</td>
        <td scope="row">14</td>
        <td scope="row">11.92%</td>
        <td scope="row">-14.12%</td>
      </tr>
      <tr>
        <td scope="row">AAPL</td>
        <td scope="row">Jun-Sep</td>
        <td scope="row">12</td>
        <td scope="row">2</td>
        <td scope="row">14</td>
        <td scope="row">16.36%</td>
        <td scope="row">-11.55%</td>
      </tr>
    </tbody>
  </table>



  {% endblock %}

ProjMyWebsite/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

  {% if item %}
  <div class="container">

    <form class="form my-2 my-lg-0" method="POST">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="text" placeholder="{{ item.item }}"
        value="{{item.item}}" aria-lable="Search" name="item">
      <input type="hidden" value="{{ item.completed }}" name="completed">
      <br>
      <button class="btn btn-secondary" type="submit">Enter</button>
      <button class="btn btn-secondary " type="button" value="Cancel">
        <a href="{% url 'todolist:todolist' %}" style="color:white">Cancel</a></button>

    </form>
  </div>
  {% endif %}

</div>
{% endblock %}

ProjMyWebsite/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Home Page</h1>


{% endblock %}

ProjMyWebsite/templates/samples.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Here are some samples:</h1>
    <!-- Start of bullet items -->
    <ul>
      <li><a href="{% url 'corrstudy:corrstudy' %}">SPY Underlying Seasonality Study</a>
        <ul>
          <li> <a href="https://github.com/1sandovalgerardo/SPY_Underlying_Study"> Study Source Code </a> </li>
        </ul>
      </li>
      <li> <a href="{% url 'todolist:todolist' %}">To Do List</a> </li>
        <ul>
          <li><a href="https://github.com/1sandovalgerardo/SandovalWebsite/tree/master/ProjMyWebsite/AppToDo">
           To Do List Source Code</a>
          </li>
       </ul>
      </li>
      <li> <a href="{% url 'blog:postmodel_list' %}">Blog</a> </li>
        <ul>
          <li> <a href="https://github.com/1sandovalgerardo/SandovalWebsite/tree/master/ProjMyWebsite/AppBlog">
            Blog Source Code </a>
          </li>
        </ul>
      </li>
    </ul>
    <!-- End of bullet items -->
  </div>
</div>
{% endblock %}
<a href="#"></a>

ProjMyWebsite/templates/todolist.html
{% extends 'base.html' %}
  {% block content %}
  <div class="container">

    <form class="form my-2 my-lg-0" method="POST">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Enter Task" aria-label="Search"
      name="item" maxlength="75"><br>
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Add Task</button>
    </form>
    <br>

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissable" role="alert">
          <button class="close" data-dismiss='alert'>X</button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}

    {% if all_items %}
      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Task</th>
            <th scope="col"><center>Completed</center></th>
            <th scope="col"><center>Edit Task</center></th>
            <th scope="col"><center>Delete Task</center></th>

          </tr>
        </thead>
        <tbody>
          {% for things in all_items %}
            {% if things.completed %}
              <tr class="table-secondary">
              <td class="striker">{{ things.item }}</td>
              <td><center> <a href="{% url 'todolist:uncross' pk=things.id %}">Yes</a> </center></td>
              <td><center> <a href="{% url 'todolist:edit' pk=things.id %}">Edit</a> </center></td>
              <td><center> <a href="{% url 'todolist:delete' pk=things.id %}"> Delete</a></center></td>
              </tr>
            {% else %}
              <tr>
              <td> {{ things.item }}</td>
              <td><center> <a href="{% url 'todolist:cross_off' pk=things.id %}">No</a> </center></td>
              <td><center> <a href="{% url 'todolist:edit' pk=things.id %}">Edit</a> </center></td>
              <td><center> <a href="{% url 'todolist:delete' pk=things.id %}"> Delete</a></center></td>
              </tr>
            {% endif %}
          {% endfor %}
        </tbody>
    </table>

    {% endif %}
  </div>

  {% endblock %}